# Required secrets
#   UNITY_LICENSE: The contents of Unity license file
#   UNITY_EMAIL: Unity user email to login
#   UNITY_PASSWORD: Unity user password to login
name: 🚀 Deploy

on:
  workflow_call:
    secrets:
      UNITY_LICENSE:
        description: The contents of Unity license file
        required: true
  workflow_dispatch:

jobs:
  # code-coverage:
  #   name: 🔍 Code Coverage
  #   uses: ./.github/workflows/build_code_coverage.yml
  #   secrets:
  #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #   permissions:
  #     contents: read
  #     checks: write

  demo:
    name: 🎮 Demo
    uses: ./.github/workflows/build_demo_player.yml
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    permissions:
      contents: read

  doc:
    name: 📘 Doc
    uses: ./.github/workflows/build_documentation.yml
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    permissions:
      contents: read

  deploy:
    name: 🚀 Deploy
    needs: [demo, doc]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: 📦 Download Artifacts To '_site'
        uses: actions/download-artifact@v4
        with:
          path: _site

      - name: 🚚 Move Documentation Files To '_site'
        run: |
          mv _site/Documentation_*  _site/
          rm -r _site/Documentation

      - name: 📦 Upload '_site'
        uses: actions/upload-pages-artifact@v3

      - name: 🚀 Deploy To GitHub Pages
        uses: actions/deploy-pages@v4
